name: ci-Moseiik

# Triggering workflow events
on:
  push:
    branches:
      - main          
  pull_request:
    branches:
      - main       

jobs:
  test:
    runs-on: ubuntu-latest                          
    strategy:
      matrix:
        platform: [linux/arm64, linux/amd64]        
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Qemu installation
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build
        run: docker buildx build --platform ${{ matrix.platform }} -t moseiik-test:latest -f docker/Dockerfile --load 

      - name: Test
        run: docker run --platform ${{ matrix.platform }} moseiik-test:latest
